/** @format */

import { Color } from '@common';

const recommendationUiTokens = {
  spacing: {
    screenHorizontal: 16,
    sectionGap: 20,
    cardPadding: 14,
    contentBottom: 28,
    questionnaireVertical: 16,
    questionnaireHeaderTop: 14,
  },
  radius: {
    card: 18,
    smallCard: 16,
    pill: 12,
    avatar: 44,
  },
  shadow: {
    card: {
      shadowColor: '#0B1220',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 10,
      elevation: 2,
    },
    footer: {
      shadowColor: '#0B1220',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.07,
      shadowRadius: 8,
      elevation: 3,
    },
  },
  typography: {
    displayName: {
      fontSize: 32,
      lineHeight: 38,
      fontWeight: '700',
    },
    sectionTitle: {
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '700',
    },
    cardTitle: {
      fontSize: 17,
      lineHeight: 22,
      fontWeight: '700',
    },
    cardSubtitle: {
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '500',
    },
    meta: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '500',
    },
    questionnaireTitle: {
      fontSize: 30,
      lineHeight: 36,
      fontWeight: '700',
    },
    questionnaireSubtitle: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '500',
    },
    questionHeadline: {
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '700',
    },
    helper: {
      fontSize: 14,
      lineHeight: 21,
      fontWeight: '500',
    },
    buttonLabel: {
      fontSize: 16,
      lineHeight: 22,
      fontWeight: '700',
    },
  },
  questionnaire: {
    background: '#F6F8F9',
    sheetRadius: 20,
    sectionRadius: 18,
    optionRadius: 18,
    optionMinHeight: 58,
    optionPaddingHorizontal: 18,
    optionPaddingVertical: 16,
    progressHeight: 4,
    footerRadius: 18,
    actionHeight: 48,
    ghostBorderColor: '#dbe2ea',
    progressTrackColor: '#dfe5eb',
    progressFillColor: Color.primary,
    sectionSeparator: '#e3e9ef',
    contentTopGap: 8,
    contentBottomGap: 18,
    footerBorderColor: '#dbe3ea',
    contactFieldGap: 16,
    contactInputRadius: 16,
    contactInputBorderColor: '#e1e7ee',
    contactSubtitleColor: '#6b7684',
    contactOptionalLabelColor: '#5f6c7d',
    privacyTextColor: '#748090',
    secondaryText: '#77808c',
    secondaryTextAndroid: '#5f6b7a',
    mutedText: '#7d8794',
    mutedTextAndroid: '#556273',
    selectAnimation: {
      shrinkScale: 0.982,
      shrinkDuration: 60,
      springFriction: 7,
      springTension: 240,
    },
  },
  resultsCard: {
    padding: 12,
    radius: 12,
    imageSize: 92,
    gap: 10,
    rowMinHeight: 96,
    borderColor: '#e7edf3',
    background: '#fff',
    titleSize: 15,
    titleLineHeightIos: 21,
    titleLineHeightAndroid: 20,
    metaSize: 12,
    metaLineHeightIos: 17,
    metaLineHeightAndroid: 16,
    priceSize: 15,
    priceLineHeightIos: 20,
    priceLineHeightAndroid: 19,
    chipRadius: 10,
    chipBg: '#f4f7fa',
    chipBorder: '#e7edf3',
    chipTextSize: 11,
    chipTextLineHeightIos: 14,
    chipTextLineHeightAndroid: 13,
    badgeBg: '#f3f7fb',
    badgeText: '#5a6878',
    badgeTextSize: 11,
    placeholderBg: '#f2f4f7',
    detailText: '#46576a',
    detailTextSize: 12,
    detailTextLineHeightIos: 17,
    detailTextLineHeightAndroid: 16,
    reasonText: '#5f6b79',
    reasonTextSize: 12,
    reasonTextLineHeightIos: 17,
    reasonTextLineHeightAndroid: 16,
    typeBadgeBg: '#f3f7fb',
    typeBadgeText: '#5a6878',
    topBadgeBg: 'rgba(63,193,190,0.13)',
    topBadgeText: '#2d7a78',
    budgetBadgeBg: '#eef9f1',
    budgetBadgeText: '#2d8a52',
    shadow: {
      shadowColor: '#0B1220',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 5,
      elevation: 2,
    },
  },
  resultsSort: {
    marginHorizontal: 12,
    marginTop: 8,
    marginBottom: 8,
    minHeight: 42,
    chipHeight: 34,
    chipRadius: 17,
    chipPaddingHorizontal: 12,
    chipBg: '#ffffff',
    chipBorder: '#dfe6ee',
    chipActiveBg: 'rgba(63,193,190,0.14)',
    chipActiveBorder: Color.primary,
    orderBtnWidth: 74,
    orderBtnBg: '#ffffff',
    orderBtnBorder: '#dfe6ee',
    orderBtnText: '#546274',
  },
  matchBar: {
    height: 6,
    trackColor: '#e5ebf1',
    fillColor: Color.primary,
    radius: 999,
  },
  specialistBanner: {
    marginTop: 8,
    marginBottom: 10,
    padding: 12,
    borderRadius: 12,
    borderColor: '#e4ebf2',
    backgroundColor: '#fff',
    ctaBorderColor: '#d9e2ea',
    ctaTextColor: '#3f4e63',
  },
};

export default recommendationUiTokens;
