/** @format */

export default {
  authTitle: 'Recomandări personalizate',
  authSubtitle:
    'Răspunde la câteva întrebări și primești recomandări generate de server.',
  authWelcome: 'Bine ai venit',
  authBrandSlogan: 'Open The World',
  authNameFallback: 'în experiența Butterfly',
  authHeroTitle: 'Hai să începem acum',
  authHeroSubtitle:
    'Selectează un chestionar, răspunde rapid și primești recomandări personalizate.',
  authHeroValueProposition:
    'Găsește recomandarea potrivită în mai puțin de un minut.',
  authHeroPrimaryAction: 'Începe chestionarul',
  authHeroSecondaryAction: 'Vezi toate chestionarele',
  authHeroAction: 'Pornește chestionarul',
  authMenuHeaderTitle: 'Recomandări Butterfly',
  authQuestionnairesLoading: 'Se încarcă lista de chestionare...',
  authQuestionnairesTitle: 'Chestionare disponibile',
  authQuestionnairesSectionTitle: 'Selectează tipul de test',
  authQuestionnaireFallback: 'Nu există chestionare active în acest moment.',
  authQuestionnaireTitleFallback: 'Chestionar recomandări',
  authQuestionnaireDescription:
    'Flux de test pentru recomandări personalizate Butterfly.',
  authQuestionnaireSelect: 'Selectează',
  authQuestionnaireSelected: 'Selectat',
  authQuestionnaireStart: 'Începe',
  authQuestionnaireContinue: 'Continuă cu selecția',
  authQuestionnaireMissing: 'Selectează un chestionar înainte să continui.',
  authGreetingDefault: 'prenume',
  authHistoryTitle: 'Istoric recent',
  authHistoryEmpty: 'Nu ai sesiuni salvate încă.',
  authHistoryEmptyAction: 'Începe primul test',
  authHistoryQuestionnaireLabel: 'Chestionar',
  authHistoryResultLabel: 'Rezultat',
  authHistoryProductsLabel: 'Produse',
  authHistoryPackagesLabel: 'Pachete',
  authContinue: 'Continuă',
  authRetry: 'Reîncearcă',
  authLoading: 'Se pregătește autentificarea...',
  authMissingFirebase:
    'Configurarea Firebase lipsește. Completează variabilele Firebase și încearcă din nou.',

  questionnaireTitle: 'Chestionar recomandări',
  questionnaireFinalTitle: 'Chestionar final',
  questionnaireStepOf: 'Pasul {{current}} din {{total}}',
  questionnaireLibraryTitle: 'Toate tipurile de test',
  questionnaireLibraryLoading: 'Se încarcă tipurile de test...',
  questionnaireLibraryEmpty: 'Nu există tipuri de test disponibile.',
  questionnaireLibraryOpen: 'Începe acest test',
  questionnaireNoActive: 'Nu există momentan un chestionar activ.',
  questionnaireLoading: 'Se încarcă întrebările...',
  questionnaireHeaderLabel: 'Întrebări',
  questionnaireBackToMenu: 'Meniu',
  questionnaireNext: 'Următorul',
  questionnaireBack: 'Înapoi',
  questionnaireFinish: 'Vezi recomandările',
  questionnaireContactTitle: 'Primește recomandarea ta',
  questionnaireContactSubtitle: 'Completează datele pentru a vedea rezultatul.',
  questionnaireContactOptionalSection: 'Vrei să ne spui ceva în plus?',
  questionnaireContactPrivacy:
    'Datele tale sunt folosite doar pentru recomandarea personalizată.',
  questionnaireContactName: 'Nume complet',
  questionnaireContactEmail: 'Email',
  questionnaireContactPhone: 'Telefon (opțional)',
  questionnaireContactNote: 'Mesaj pentru specialist (opțional)',
  questionnaireContactNamePlaceholder: 'Ex: Andrei Popescu',
  questionnaireContactEmailPlaceholder: 'Ex: andrei@email.ro',
  questionnaireContactPhonePlaceholder: 'Ex: 07xxxxxxxx',
  questionnaireContactNotePlaceholder: 'Spune-ne ce cauți.',
  questionnaireBudgetMinLabel: 'Valoare minimă',
  questionnaireBudgetMaxLabel: 'Valoare maximă',
  questionnaireBudgetMinPlaceholder: '0',
  questionnaireBudgetMaxPlaceholder: '2000',
  questionnaireBudgetInvalidRange:
    'Valoarea minimă trebuie să fie mai mică sau egală cu valoarea maximă.',
  questionnaireRequired: 'Acest câmp este obligatoriu.',
  questionnaireInvalidEmail: 'Adresa de email nu este validă.',
  questionnaireFinalizeLoading: 'Se calculează recomandările...',
  microLoadingTitle: 'Analizăm răspunsurile…',
  microLoadingSubtitle:
    'Comparăm stilul tău, distanța, prioritatea și bugetul cu produsele disponibile.',
  microLoadingStepOne: 'Interpretăm preferințele',
  microLoadingStepTwo: 'Selectăm produse compatibile',
  microLoadingStepThree: 'Calculăm potrivirea + bugetul',
  microLoadingTimeout:
    'Procesarea durează prea mult. Te rugăm să încerci din nou.',

  resultsTab: 'Rezultate',
  favoritesTab: 'Favorite',
  historyTab: 'Istoric',
  resultsTitle: 'Rezultatele tale',
  resultsModeProducts: 'Produse recomandate',
  resultsModePackages: 'Pachete recomandate',
  resultsEmpty: 'Nu există rezultate pentru răspunsurile curente.',
  resultsSortBy: 'Sortează după',
  resultsSortDirection: 'Ordine',
  resultsSortAsc: 'Crescător',
  resultsSortDesc: 'Descrescător',
  resultsSortFit: 'Potrivire',
  resultsSortPrice: 'Preț',
  resultsSortSpeed: 'Viteză',
  resultsSortSpin: 'Spin',
  resultsSortControl: 'Control',
  resultsSortOrderAscShort: 'Asc',
  resultsSortOrderDescShort: 'Desc',
  resultsOpenDetails: 'Detalii',
  resultsCardBadgeProduct: 'Produs',
  resultsCardBadgePackage: 'Pachet',
  resultsCardDetailsCta: 'Detalii',
  resultsTopRecommendationBadge: '#1 Recomandarea ta',
  resultsInBudgetBadge: 'În buget',
  resultsMatchLabel: 'Potrivire',
  resultsSuggestionLead: "S-ar putea să-ți placă...",
  resultsWhyFit: 'De ce se potrivește',
  resultsWowGreetingFallbackName: 'jucător',
  resultsWowTitle: 'Rezultatul tău personalizat',
  resultsWowSubtitle: 'Top recomandări pentru stilul și bugetul tău.',
  resultsOtherRecommendations: 'Alte recomandări',
  resultsBuildConfigurator: 'Construiește setup-ul tău',
  resultsAnswersSummaryTitle: 'Rezumat răspunsuri',
  resultsAnswersSummaryShow: 'Arată',
  resultsAnswersSummaryHide: 'Ascunde',
  resultsReasonFallback: 'Potrivire bună pentru răspunsurile tale.',
  resultsSpecialistBannerTitle: 'Vrei confirmare de la specialist?',
  resultsSpecialistBannerSubtitle:
    'Primești feedback personalizat pe baza recomandărilor de mai sus.',
  resultsAskSpecialist: 'Contactează specialist',
  resultsRefreshFromHistory: 'Recalculează din istoric',
  resultsDebug: 'Diagnostic (dev)',

  favoriteAdd: 'Adaugă la favorite',
  favoriteRemove: 'Elimină din favorite',
  favoriteAdded: 'Adaugat la favorite',
  favoriteRemoved: 'Eliminat din favorite',
  favoritesTitle: 'Produse favorite',
  favoritesEmpty: 'Nu ai adăugat produse la favorite.',

  historyTitle: 'Istoric sesiuni',
  historyLibraryTitle: 'Toate sesiunile',
  historyEmpty: 'Nu există sesiuni salvate în istoric.',
  historyCardQuestionnaire: 'Chestionar',
  historyCardMode: 'Mod',
  historyCardProducts: 'Produse',
  historyCardPackages: 'Pachete',
  historyUseSession: 'Folosește această sesiune',
  historyRecompute: 'Recalculează',
  historyRecomputeLoading: 'Se recalculează...',

  detailTitle: 'Detalii recomandare',
  detailOpenProduct: 'Deschide pagina produsului',
  detailPrice: 'Preț',
  detailFitScore: 'Scor potrivire',
  detailMatchPercent: 'Procent potrivire',
  detailAttributes: 'Atribute',
  detailScenario: 'Scenariu',

  specialistTitle: 'Cerere către specialist',
  specialistSubtitle:
    'Trimite această recomandare către specialist pentru feedback personalizat.',
  specialistSubmit: 'Trimite cererea',
  specialistSubmitting: 'Se trimite cererea...',
  specialistSuccess:
    'Cererea a fost trimisă cu succes. Vei primi răspuns în curând.',
  specialistMissingUser:
    'Nu există utilizator autentificat pentru trimiterea cererii.',
  configuratorTitle: 'Configurator (în curând)',
  configuratorSubtitle:
    'Pregătim experiența completă pentru construirea setup-ului tău.',
  configuratorSelectedProduct: 'Produs selectat',
  configuratorAnswersSummary: 'Rezumat răspunsuri',

  callableUnauthenticated:
    'Trebuie să fii autentificat pentru a primi recomandări.',
  callableInvalidArgument:
    'Datele trimise sunt invalide. Verifică răspunsurile și încearcă din nou.',
  callableUnavailable:
    'Serviciul de recomandări este indisponibil momentan. Încearcă din nou.',
  callableGeneric:
    'A apărut o eroare la calculul recomandărilor. Te rugăm să reîncerci.',

  commonRetry: 'Reîncearcă',
  commonLoading: 'Se încarcă...',
  commonViewAll: 'Vezi toate',
  commonUnknown: 'Necunoscut',
  commonQuestion: 'Întrebare',
};
